# Generated by Django 5.1.3 on 2024-11-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tag_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tag',
            new_name='tags',
        ),
    ]
